"""
Definition:
Lightweight MINIM-compatible mock backend.
---
Results:
Simulates model training and generation while leaving evaluation to the normal metrics layer.
"""

from __future__ import annotations

import csv
import hashlib
import json
import logging
import random
import subprocess
import sys
from pathlib import Path
from typing import TYPE_CHECKING

from PIL import Image, ImageDraw

if TYPE_CHECKING:
    from minim.runs import PreparedRun

logger = logging.getLogger(__name__)

MOCK_BASE_MODEL_DIR = Path("models/base/mock-minim")
MOCK_BASE_MODEL_METADATA = MOCK_BASE_MODEL_DIR / "model.json"


def resolve_mock_base_model(base_model: str | None = None) -> str:
    if base_model is not None:
        return base_model
    if not MOCK_BASE_MODEL_METADATA.exists():
        raise RuntimeError(
            f"Mock base model metadata is missing at '{MOCK_BASE_MODEL_METADATA}'. "
            "Create the mock model descriptor under models/base/mock-minim before "
            "using --backend mock."
        )
    return str(MOCK_BASE_MODEL_DIR)


def _manifest_rows(manifest_path: Path) -> list[dict[str, str]]:
    with Path.open(manifest_path, encoding="utf-8", newline="") as file:
        return list(csv.DictReader(file))


def _prompt_digest(row: dict[str, str], seed: int | None) -> bytes:
    prompt = f"{row.get('modality', '')}:{row.get('text', '')}:{row.get('patient_id', '')}:{seed}"
    return hashlib.sha256(prompt.encode("utf-8")).digest()


def _write_placeholder_image(row: dict[str, str], output_path: Path, seed: int | None) -> None:
    digest = _prompt_digest(row, seed)
    rng_seed = int.from_bytes(digest[:8], byteorder="big", signed=False)
    rng = random.Random(rng_seed)
    base = tuple(int(value) for value in digest[:3])
    accent = tuple(int(value) for value in digest[3:6])
    image = Image.new("RGB", (128, 128), base)
    draw = ImageDraw.Draw(image)
    for index in range(0, 128, 16):
        jitter = rng.randint(-48, 48)
        color = tuple(
            (accent[channel] + index * (channel + 1) + jitter) % 256
            for channel in range(3)
        )
        draw.rectangle((index, 0, index + 8, 127), fill=color)
    for _ in range(12):
        x0 = rng.randint(0, 112)
        y0 = rng.randint(0, 112)
        width = rng.randint(8, 32)
        height = rng.randint(8, 32)
        color = tuple(rng.randint(0, 255) for _ in range(3))
        draw.rectangle((x0, y0, min(127, x0 + width), min(127, y0 + height)), outline=color)
    draw.text((8, 56), row.get("dataset", "mock")[:12], fill=(255, 255, 255))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    image.save(output_path)


class MockMinimBackend:
    name = "mock"

    def train(
        self,
        prepared_run: "PreparedRun",
        *,
        base_model: str | None = None,
        num_train_epochs: int = 5,
        max_train_steps: int | None = None,
        learning_rate: float = 1e-5,
        train_batch_size: int = 1,
        gradient_accumulation_steps: int = 1,
        resolution: int = 512,
        seed: int = 42,
        mixed_precision: str | None = None,
        validation_epochs: int = 5,
        report_to: str = "tensorboard",
    ) -> subprocess.CompletedProcess:
        resolved_base_model = resolve_mock_base_model(base_model)
        train_rows = _manifest_rows(prepared_run.train_manifest)
        val_rows = _manifest_rows(prepared_run.val_manifest)
        prepared_run.model_dir.mkdir(parents=True, exist_ok=True)
        model_card = {
            "backend": self.name,
            "run_name": prepared_run.run_name,
            "base_model": resolved_base_model,
            "train_rows": len(train_rows),
            "validation_rows": len(val_rows),
            "num_train_epochs": num_train_epochs,
            "max_train_steps": max_train_steps,
            "learning_rate": learning_rate,
            "train_batch_size": train_batch_size,
            "gradient_accumulation_steps": gradient_accumulation_steps,
            "resolution": resolution,
            "seed": seed,
            "mixed_precision": mixed_precision,
            "validation_epochs": validation_epochs,
            "report_to": report_to,
        }
        (prepared_run.model_dir / "mock_model.json").write_text(
            json.dumps(model_card, indent=2), encoding="utf-8"
        )
        (prepared_run.model_dir / "README.md").write_text(
            "# Mock MINIM checkpoint\n\nThis directory was generated by the lightweight mock backend for pipeline validation.\n",
            encoding="utf-8",
        )
        logger.info(
            "Mock MINIM training completed for run '%s'.", prepared_run.run_name
        )
        logger.info("Mock base model source: %s", resolved_base_model)
        logger.info("Mock checkpoint output: %s", prepared_run.model_dir)
        return subprocess.CompletedProcess(args=[sys.executable, "-m", "minim.backends.mock", "train"], returncode=0)

    def generate(
        self,
        prepared_run: "PreparedRun",
        *,
        device: str | None = None,
        seed: int | None = 42,
        num_inference_steps: int = 50,
        guidance_scale: float = 7.5,
    ) -> list[Path]:
        rows = _manifest_rows(prepared_run.test_manifest)
        prepared_run.generated_test_dir.mkdir(parents=True, exist_ok=True)
        generation_card = {
            "backend": self.name,
            "seed": seed,
            "device": device,
            "num_inference_steps": num_inference_steps,
            "guidance_scale": guidance_scale,
            "sample_count": len(rows),
        }
        (prepared_run.eval_dir / "mock_generation.json").write_text(
            json.dumps(generation_card, indent=2), encoding="utf-8"
        )
        output_paths: list[Path] = []
        for index, row in enumerate(rows):
            output_path = prepared_run.generated_test_dir / f"{index:05d}.png"
            _write_placeholder_image(row, output_path, seed)
            output_paths.append(output_path)

        logger.info("Mock generated samples: %s", prepared_run.generated_test_dir)
        return output_paths
